"""Crafting recipe lookup, loaded from the bundled recipes.json.

recipes.json is generated by extract_recipes.py from ao-bin-dumps items.json.
Maps a price-API gear id -> {"materials": [{"id", "count", "ret"}, ...]} where
material ids are already in AODP form (enchanted mats carry the @level suffix)
and `ret` is False for artifacts/tokens that the return rate never refunds.
"""
import json
import os
import sys

_RECIPES: dict | None = None


def _recipes_path() -> str:
    """Find recipes.json — works in dev and after a PyInstaller --onefile bundle."""
    candidates = []
    if hasattr(sys, "_MEIPASS"):
        candidates.append(os.path.join(sys._MEIPASS, "recipes.json"))
    candidates.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "recipes.json"))
    for p in candidates:
        if os.path.exists(p):
            return p
    raise FileNotFoundError("recipes.json not found; bundle it with the app")


def _load():
    global _RECIPES
    if _RECIPES is None:
        with open(_recipes_path(), "r", encoding="utf-8") as f:
            _RECIPES = json.load(f)


def get_recipe(item_id: str) -> dict | None:
    """Recipe for a gear id (e.g. 'T4_MAIN_SWORD' or 'T5_2H_AXE@2'), or None."""
    _load()
    return _RECIPES.get(item_id)


def has_recipe(item_id: str) -> bool:
    _load()
    return item_id in _RECIPES
